<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Manual • drexplorer2</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.3/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Manual">
<meta property="og:description" content="drexplorer2">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-115082821-1"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-115082821-1');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">drexplorer2</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.1.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/ALL.html">Articles</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/lshen1/drexplorer2/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right hidden-xs hidden-sm" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Manual</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/lshen1/drexplorer2/blob/master/vignettes/ALL.Rmd"><code>vignettes/ALL.Rmd</code></a></small>
      <div class="hidden name"><code>ALL.Rmd</code></div>

    </div>

    
    
<div id="qc-outlier-identification" class="section level1">
<h1 class="hasAnchor">
<a href="#qc-outlier-identification" class="anchor"></a>[QC] Outlier Identification]</h1>
<p>This package implements the method by Newman, D. The test statistic q=w/s where w is the range of the data and s is sample standard deviation estimated from controls. The null distribution for q has been derived and 1% and 5% quantiles have been given in the paper.</p>
<p>We implement this procedure. In particular, <code><a href="../reference/NewmanTest.html">NewmanTest()</a></code> returns a logic vector specifying whether the observations are outliers.</p>
<p>Usually, drug-response data contains multiple doses. Therefore, we write a wrapper <code><a href="../reference/drOutlier.html">drOutlier()</a></code> that compute the result for all doses one dose at a time.</p>
<p>We use the <em>ryegrass</em> data from <strong>drc</strong> package for illustration purpose. The <em>ryegrass</em> data was originally published by <a href="#Streibig2002ryegrass">(Streibig et al. 2002)</a> which contains 24 concentrations of ferulic acid (a root growth inhibitor) and corresponding root length.</p>
<p>First, we load the <strong>drexplorer</strong> package and attach the  data.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)

<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">ryegrass</span>)
<span class="no">dose</span> <span class="kw">&lt;-</span> <span class="no">ryegrass</span>[, <span class="fl">2</span>]
<span class="no">response</span> <span class="kw">&lt;-</span> <span class="no">ryegrass</span>[, <span class="fl">1</span>]</pre></body></html>
<p>At dose=3.75 and significance level 0.05, we find there is one outlier identified:</p>
<html><body><pre class="r"><span class="co">## potential outlier at dose 3.75</span>
<span class="fu"><a href="../reference/NewmanTest.html">NewmanTest</a></span>(<span class="kw">ref</span> <span class="kw">=</span> <span class="no">response</span>[<span class="no">dose</span> <span class="kw">==</span> <span class="fl">0</span>], <span class="kw">obs</span> <span class="kw">=</span> <span class="no">response</span>[<span class="no">dose</span> <span class="kw">==</span> <span class="fl">3.75</span>], <span class="kw">alpha</span>  <span class="kw">=</span><span class="fl">0.05</span>)
<span class="co">#&gt; [1] FALSE FALSE  TRUE</span></pre></body></html>
<p>We also examine all dose levels and find no further outliers:</p>
<html><body><pre class="r"><span class="fu"><a href="../reference/drOutlier.html">drOutlier</a></span>(<span class="kw">drMat</span> <span class="kw">=</span> <span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)], <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">0.05</span>)
<span class="co">#&gt;  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</span>
<span class="co">#&gt; [13] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</span></pre></body></html>
</div>
<div id="qc-assessing-reproducibility" class="section level1">
<h1 class="hasAnchor">
<a href="#qc-assessing-reproducibility" class="anchor"></a>[QC] Assessing Reproducibility</h1>
<p>Sometimes replicated viability assays are performed. In such case, it is useful to examine if the experiments are reproducible.</p>
<p>A good metric is the <strong>Concordance Correlation Coefficient (CCC)</strong> that captures both the location shift as well as scale shift between the replicates. The <code>plotCCC</code> function can be used to compute CCC and visualize the replicated data.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)

<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="fl">100</span>)
<span class="no">r1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span>(<span class="fl">28</span>)
<span class="no">r2</span> <span class="kw">&lt;-</span> <span class="no">r1</span>+<span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span>(<span class="fl">28</span>, <span class="fl">0</span>, <span class="fl">0.1</span>)
<span class="no">ccc</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotCCC.html">plotCCC</a></span>(<span class="no">r1</span>, <span class="no">r2</span>,
               <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">'Simulated response, replicate 1'</span>,
               <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">'Simulated response, replicate 2'</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-4-1.png" width="4800" style="display: block; margin: auto;"></p>
<html><body><pre class="r"><span class="no">ccc</span>
<span class="co">#&gt;     ccc s_shift l_shift  ccc_lo  ccc_hi      Cb    corr  mean_x  mean_y    sd_x </span>
<span class="co">#&gt;  0.9337  0.9765  0.0758  0.8626  0.9686  0.9969  0.9366  0.5012  0.5182  0.2314 </span>
<span class="co">#&gt;    sd_y </span>
<span class="co">#&gt;  0.2259</span></pre></body></html>
<p>Here we have simulated two response vectors and calculate CCC. The computed CCC value is 0.934, location shift is 0.076, scale shift is 0.976, Pearson correlation is 0.937.</p>
</div>
<div id="single-drug-fit-dose-response-models" class="section level1">
<h1 class="hasAnchor">
<a href="#single-drug-fit-dose-response-models" class="anchor"></a>[Single Drug] Fit Dose-Response Models</h1>
<p>Below we show how to fit a dose-response model. The <code><a href="../reference/drFit.html">drFit()</a></code> function is a wrapper to the <strong>drc</strong> and <strong>DoseFinding</strong> packages. Therefore, all models implemented by either package can be fitted. A model is specified by a <em>modelName</em> to be passed to this function.</p>
<p>Outliers can be identified and removed from model fitting by specifying the parameter alpha (either at significance level of 0.01 or 0.05). To disable outlier identification, set <em>alpha=1</em>.</p>
<p>To remove controls (responses at dose=0) during model fitting, we can set <em>fitCtr=FALSE</em>.</p>
<p>Note that the responses are scaled by mean response at dose=0 before model fitting.</p>
<p>Below we fit a sigmaEmax model. We set <em>alpha=1</em> to disable outlier removal and <em>fitCtr=FALSE</em> to exclude controls.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)

<span class="no">fit_sigEmax_alpha1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/drFit.html">drFit</a></span>(<span class="kw">drMat</span> <span class="kw">=</span> <span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)],
                            <span class="kw">modelName</span> <span class="kw">=</span> <span class="st">"sigEmax"</span>,
                            <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">fitCtr</span> <span class="kw">=</span> <span class="fl">FALSE</span>)</pre></body></html>
<p>The result is slightly different when outliers passing significance level of 0.05 is removed.</p>
<html><body><pre class="r"><span class="no">fit_sigEmax_alpha_o5</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/drFit.html">drFit</a></span>(<span class="kw">drMat</span> <span class="kw">=</span> <span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)],
                              <span class="kw">modelName</span> <span class="kw">=</span> <span class="st">"sigEmax"</span>,
                              <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">fitCtr</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="no">fit_sigEmax_alpha1</span>@<span class="kw">fit</span>
<span class="co">#&gt; Dose Response Model</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Model: sigEmax </span>
<span class="co">#&gt; Fit-type: normal </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Coefficients dose-response model</span>
<span class="co">#&gt;    e0  eMax  ed50     h </span>
<span class="co">#&gt;  1.03 -0.97  2.99  2.81 </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Degrees of freedom: 14 </span>
<span class="co">#&gt; Residual standard error: 0.073</span>
<span class="no">fit_sigEmax_alpha_o5</span>@<span class="kw">fit</span>
<span class="co">#&gt; Dose Response Model</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Model: sigEmax </span>
<span class="co">#&gt; Fit-type: normal </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Coefficients dose-response model</span>
<span class="co">#&gt;     e0   eMax   ed50      h </span>
<span class="co">#&gt;  1.017 -0.945  2.789  3.384 </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Degrees of freedom: 13 </span>
<span class="co">#&gt; Residual standard error: 0.0567</span></pre></body></html>
<div id="predict-response" class="section level2">
<h2 class="hasAnchor">
<a href="#predict-response" class="anchor"></a>- Predict response</h2>
<p>One a model is fitted, it can be used to make predictions.</p>
<p>Below we make predictions at the observed dose levels with a previously fitted model. Since the responses are scaled by mean response at dose=0 in model fitting, the predicted responses are also scaled by the mean response from controls. By default, the predict function makes predictions at observed doses.</p>
<html><body><pre class="r"><span class="no">y</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/predict-methods.html">predict</a></span>(<span class="no">fit_sigEmax_alpha_o5</span>)
<span class="no">y</span>
<span class="co">#&gt;      1      2      3      4      5      6      7      8      9     10     11 </span>
<span class="co">#&gt; 1.0174 1.0174 1.0174 1.0174 1.0174 1.0174 0.9942 0.9942 0.9942 0.8205 0.8205 </span>
<span class="co">#&gt;     12     13     14     15     16     17     18     19     20     21     22 </span>
<span class="co">#&gt; 0.8205 0.3262 0.3262 0.3262 0.1045 0.1045 0.1045 0.0756 0.0756 0.0756 0.0727 </span>
<span class="co">#&gt;     23     24 </span>
<span class="co">#&gt; 0.0727 0.0727</span></pre></body></html>
</div>
<div id="obtain-ic-values" class="section level2">
<h2 class="hasAnchor">
<a href="#obtain-ic-values" class="anchor"></a>- Obtain IC values</h2>
<p>We implement two approaches for IC value computation. One is to interpolate the observed dosages and try to use the dose that has the predicted response closest to the specified percentile of IC value.</p>
<p>The second approach is to use root finding by setting the fitted model to equal to the specified percentile. In most cases, the result are similar. However, the latter approach may give IC50 values beyond observed dosages and sometimes not robust. Further, a specified IC might be not achievable for the fitted model, in which case the returned dose is either -Inf (a flagger for percentile being too small to be achieved) or Inf (a flagger for percentile being too large to be achieved). The <code><a href="../reference/computeIC.html">computeIC()</a></code> function implements both approaches. By setting <em>interpolation=TRUE</em> (the default value) in the <code><a href="../reference/computeIC.html">computeIC()</a></code> function, the interpolation approach will be selected.</p>
<p>Computing IC values at different quantiles is also easy. Similar to the <code><a href="../reference/drFit.html">drFit()</a></code> function, different models as well as other options (alpha and fitCtr) can be specified in estimating IC value.</p>
<p>Below we estimate IC50 at different percentiles with the sigmoid Emax model with outlier removal (alpha=0.05) fitted previously. We see that estimates from interpolation and prediction (may be extrapolated) by the model are quite similar except for IC0 and IC100. IC100 from prediction is Inf since the fitted model cannot achieve 100% killing effect (see figure below). IC100 from interpolation is the maximum dose (30 in this case) which is a truncated estimate.</p>
<p>Similarly, since IC0 is not achievable within the observed dose, the prediction estimate of 0.86 is smaller than the minimum dose (0.94). The predicted IC value has advantage over interpolated IC value in the sense that it is not truncated. However, since the value might be extrapolated (estimate being outside of observed dose range), the estimate is more variable.</p>
<html><body><pre class="r"><span class="fu"><a href="../reference/computeIC.html">computeIC</a></span>(<span class="no">fit_sigEmax_alpha_o5</span>, <span class="kw">percent</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="fl">0</span>, <span class="fl">1</span>, <span class="kw">by</span><span class="kw">=</span><span class="fl">0.1</span>), <span class="kw">log.d</span><span class="kw">=</span><span class="fl">FALSE</span>, <span class="kw">interpolation</span><span class="kw">=</span><span class="fl">TRUE</span>)
<span class="co">#&gt;   IC0  IC10  IC20  IC30  IC40  IC50  IC60  IC70  IC80  IC90 IC100 </span>
<span class="co">#&gt;  0.94  1.57  1.95  2.28  2.60  2.95  3.36  3.91  4.82  7.86 30.00</span>
<span class="fu"><a href="../reference/computeIC.html">computeIC</a></span>(<span class="no">fit_sigEmax_alpha_o5</span>, <span class="kw">percent</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="fl">0</span>, <span class="fl">1</span>, <span class="kw">by</span><span class="kw">=</span><span class="fl">0.1</span>), <span class="kw">log.d</span><span class="kw">=</span><span class="fl">FALSE</span>, <span class="kw">interpolation</span><span class="kw">=</span><span class="fl">FALSE</span>)
<span class="co">#&gt;   IC0  IC10  IC20  IC30  IC40  IC50  IC60  IC70  IC80  IC90 IC100 </span>
<span class="co">#&gt; 0.862 1.566 1.952 2.280 2.603 2.951 3.364 3.916 4.829 7.857   Inf</span></pre></body></html>
</div>
</div>
<div id="single-drug-comparing-multiple-dose-response-curves" class="section level1">
<h1 class="hasAnchor">
<a href="#single-drug-comparing-multiple-dose-response-curves" class="anchor"></a>[Single Drug] Comparing Multiple Dose-Response Curves</h1>
<p>We provide S4 generic functions (plot and lines) for fitted model. As a result, it is easy to compare different models and graphically examine outliers through multiple dose-response curves.</p>
<p>Outliers at significance levels 0.01 and 0.05 are indicated by different colors and symbols. Below we show the LL.3, LL.3u and sigEmax curves in this example corresponding to the three-parameter log-logistic model with lower limit 0, three-parameter log-logistic with upper limit 1 and the sigmoid Emax model.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">ryegrass</span>)

<span class="no">fit.LL.3</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/drFit.html">drFit</a></span>(<span class="kw">drMat</span> <span class="kw">=</span> <span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)],
                  <span class="kw">modelName</span> <span class="kw">=</span> <span class="st">"LL.3"</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">fitCtr</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="no">fit.LL.3u</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/drFit.html">drFit</a></span>(<span class="kw">drMat</span> <span class="kw">=</span> <span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)],
                   <span class="kw">modelName</span> <span class="kw">=</span> <span class="st">"LL.3u"</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">fitCtr</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="no">fit.sigEmax</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/drFit.html">drFit</a></span>(<span class="kw">drMat</span> <span class="kw">=</span> <span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)],
                     <span class="kw">modelName</span> <span class="kw">=</span> <span class="st">"sigEmax"</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">fitCtr</span> <span class="kw">=</span> <span class="fl">FALSE</span>)

<span class="fu"><a href="../reference/plot-methods.html">plot</a></span>(<span class="no">fit.LL.3</span>, <span class="kw">main</span> <span class="kw">=</span> <span class="st">''</span>, <span class="kw">col</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">2</span>)
<span class="fu"><a href="../reference/lines-methods.html">lines</a></span>(<span class="no">fit.LL.3u</span>, <span class="kw">col</span> <span class="kw">=</span> <span class="fl">5</span>, <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">2</span>)
<span class="fu"><a href="../reference/lines-methods.html">lines</a></span>(<span class="no">fit.sigEmax</span>, <span class="kw">col</span> <span class="kw">=</span> <span class="fl">6</span>, <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">2</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span>(<span class="st">"bottomleft"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'LL.3'</span>, <span class="st">'LL.3u'</span>, <span class="st">'sigEmax'</span>), <span class="kw">col</span> <span class="kw">=</span> <span class="fl">4</span>:<span class="fl">6</span>, <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">3</span>, <span class="kw">bty</span> <span class="kw">=</span> <span class="st">"n"</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-9-1.png" width="3600" style="display: block; margin: auto;"></p>
<p>With these many models fitted, which one should be preferred? One way is to look at the <strong>Residual Standard Error (RSE)</strong> as below. We see that the LL.3u model is best by the RSE criteria.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="no">fit.LL.3</span>, <span class="no">fit.LL.3u</span>, <span class="no">fit.sigEmax</span>), <span class="kw">function</span>(<span class="no">x</span>) <span class="no">x</span>@<span class="kw">info</span>$<span class="no">RSE</span>)
<span class="co">#&gt; [1] 0.0699 0.0550 0.0567</span></pre></body></html>
<p>We also compare the curves using sigEmax model with and without outlier identification.</p>
<html><body><pre class="r"><span class="co"># no outlier excluded</span>
<span class="no">fit.sigEmax0</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/drFit.html">drFit</a></span>(<span class="kw">drMat</span> <span class="kw">=</span> <span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)],
                      <span class="kw">modelName</span> <span class="kw">=</span> <span class="st">"sigEmax"</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">fitCtr</span> <span class="kw">=</span> <span class="fl">FALSE</span>)

<span class="fu"><a href="../reference/plot-methods.html">plot</a></span>(<span class="no">fit.sigEmax0</span>, <span class="kw">main</span> <span class="kw">=</span> <span class="st">'sigEmax model'</span>, <span class="kw">col</span> <span class="kw">=</span> <span class="fl">7</span>, <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">2</span>)
<span class="fu"><a href="../reference/lines-methods.html">lines</a></span>(<span class="no">fit.sigEmax</span>, <span class="kw">col</span> <span class="kw">=</span> <span class="fl">6</span>, <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">2</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span>(<span class="st">"bottomleft"</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'alpha = 0.05'</span>, <span class="st">'ignored'</span>), <span class="kw">col</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">6</span>, <span class="fl">7</span>), <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">3</span>, <span class="kw">bty</span> <span class="kw">=</span> <span class="st">"n"</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-11-1.png" width="3600" style="display: block; margin: auto;"></p>
</div>
<div id="single-drug-select-the-best-model" class="section level1">
<h1 class="hasAnchor">
<a href="#single-drug-select-the-best-model" class="anchor"></a>[Single Drug] Select the Best Model</h1>
<p>We provide a wrapper function, <code><a href="../reference/fitOneExp.html">fitOneExp()</a></code>, incorporating outlier detection, fitting multiple models, selecting the best model and estimating IC values.</p>
<p>Users can specify multiple models from the <strong>drc</strong> and <strong>DoseFinding</strong> packages using the <em>models</em> parameter. An example is shown below.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">ryegrass</span>)

<span class="no">fitExp</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/fitOneExp.html">fitOneExp</a></span>(<span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)],
                    <span class="kw">drug</span> <span class="kw">=</span> <span class="st">''</span>, <span class="kw">cellLine</span> <span class="kw">=</span> <span class="st">''</span>, <span class="kw">unit</span> <span class="kw">=</span> <span class="st">''</span>,
                    <span class="kw">models</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'sigEmax'</span>, <span class="st">'LL.4'</span>, <span class="st">'LL.5'</span>, <span class="st">'LL.3'</span>, <span class="st">'LL.3u'</span>, <span class="st">'logistic'</span>),
                    <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">interpolation</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html>
<p>The fitted models can be compared through the plotOneExp function as below:</p>
<html><body><pre class="r"><span class="fu"><a href="../reference/plotOneExp.html">plotOneExp</a></span>(<span class="no">fitExp</span>, <span class="kw">main</span> <span class="kw">=</span> <span class="st">'Dose-Response Curves from Multiple Models'</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-13-1.png" width="4320" style="display: block; margin: auto;"></p>
<p>The best model based on Residual Standard Error (RSE) can be obtained as shown below.</p>
<html><body><pre class="r"><span class="co">## This is the bast model:</span>
<span class="no">bM</span> <span class="kw">&lt;-</span> <span class="no">fitExp</span>$<span class="no">bestModel</span>
<span class="no">bM</span>
<span class="co">#&gt; [1] "LL.5"</span>

<span class="co">## RSE from all models fitted:</span>
<span class="no">fitExp</span>$<span class="no">RSEs</span>
<span class="co">#&gt;  sigEmax     LL.4     LL.5     LL.3    LL.3u logistic </span>
<span class="co">#&gt;   0.0567   0.0567   0.0548   0.0699   0.0550   0.0603</span>

<span class="co">## IC50 from all models fitted:</span>
<span class="no">fitExp</span>$<span class="no">IC50</span>
<span class="co">#&gt;  sigEmax     LL.4     LL.5     LL.3    LL.3u logistic </span>
<span class="co">#&gt;    0.470    0.470    0.432    0.488    0.471    0.480</span>

<span class="co">## best model fitted:</span>
<span class="no">fitExp</span>$<span class="no">fit</span><span class="kw">[[</span><span class="no">bM</span>]]@<span class="kw">fit</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; A 'drc' model.</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Call:</span>
<span class="co">#&gt; drc::drm(formula = response ~ dose, data = dat, fct = f())</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Coefficients:</span>
<span class="co">#&gt; b:(Intercept)  c:(Intercept)  d:(Intercept)  e:(Intercept)  f:(Intercept)  </span>
<span class="co">#&gt;       12.7423         0.0408         0.9904         1.6979         0.1229</span></pre></body></html>
</div>
<div id="single-drug-fit-hill-equation" class="section level1">
<h1 class="hasAnchor">
<a href="#single-drug-fit-hill-equation" class="anchor"></a>[Single Drug] Fit Hill Equation</h1>
<p>The Hill equation is a special dose-response model. Below we demonstrate how to specifically fit this model by <code><a href="../reference/hillFit.html">hillFit()</a></code> function.</p>
<p>We first prepare standardized data where the response is scaled to between 0 and 1. A generic plot function is implemented for the fitted object.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">ryegrass</span>)

<span class="co">## prepare standardized data</span>
<span class="no">sdat</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/prepDRdat.html">prepDRdat</a></span>(<span class="kw">drMat</span> <span class="kw">=</span> <span class="no">ryegrass</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">2</span>, <span class="fl">1</span>)],
                  <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">0.01</span>, <span class="kw">fitCtr</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">standardize</span> <span class="kw">=</span> <span class="fl">TRUE</span>)$<span class="no">dat</span>

<span class="co">## fit Hill equation</span>
<span class="no">fit_hill</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/hillFit.html">hillFit</a></span>(<span class="kw">d</span> <span class="kw">=</span> <span class="no">sdat</span>$<span class="no">dose</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">sdat</span>$<span class="no">response</span>)

<span class="fu"><a href="../reference/plot-methods.html">plot</a></span>(<span class="no">fit_hill</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-15-1.png" width="3600" style="display: block; margin: auto;"></p>
<html><body><pre class="r"><span class="no">fit_hill</span>[<span class="fl">1</span>:<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="no">fit_hill</span>)]
<span class="co">#&gt;      E0    Einf    EC50      HS    Emax     MSE     Rsq     RSE </span>
<span class="co">#&gt; 1.02918 0.05885 2.99230 2.80933 0.06034 0.00415 0.97086 0.07300</span></pre></body></html>
</div>
<div id="single-drug-fit-nci60-method" class="section level1">
<h1 class="hasAnchor">
<a href="#single-drug-fit-nci60-method" class="anchor"></a>[Single Drug] Fit NCI60 Method</h1>
<p>The NCI60 method deals with data that contains information for day 0 treatment. The response is between -1 and 1 and thus quite different from the previous analysis.</p>
<div class="figure">
<img src="../man/figures/aoc.png">
</div>
<p>Below we show how to fit models to estimate GI50, LC50, TGI, AOC_GR, AOC_LD, and AUC_GRI. Similarly, the fitted object can be visualized with a generic plot function.</p>
<blockquote>
<p>Notice that the parameter estimates for GI50, LC50 and TGI are based on original drug concentration, not log10 based. On the other hand, the calculation for area under/over curve of AOC_GR, AOC_LD, and AUC_GRI are based on log10 scale.</p>
</blockquote>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">datNCI60</span>)

<span class="no">fit_nci60</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/nci60Fit.html">nci60Fit</a></span>(<span class="kw">d</span> <span class="kw">=</span> <span class="no">datNCI60</span>$<span class="no">Dose</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">datNCI60</span>$<span class="no">Growth</span>/<span class="fl">100</span>)

<span class="fu"><a href="../reference/plot-methods.html">plot</a></span>(<span class="no">fit_nci60</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-16-1.png" width="3600" style="display: block; margin: auto;"></p>
<html><body><pre class="r"><span class="no">fit_nci60</span>[<span class="fl">1</span>:<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="no">fit_nci60</span>)]
<span class="co">#&gt;    GI50     TGI    LC50  AOC_GR  AOC_LD AUC_GRI </span>
<span class="co">#&gt;  0.0683  0.2738  0.7900  0.4298  0.0209  0.7746</span></pre></body></html>
</div>
<div id="drug-comb-drug-interaction-index" class="section level1">
<h1 class="hasAnchor">
<a href="#drug-comb-drug-interaction-index" class="anchor"></a>[Drug Comb] Drug Interaction Index</h1>
<p>Administering two drugs simultaneously might induce stronger effect than if administered separately. This is called synergism. Experiments to detect synergism (or antagonism which is the opposite) are usually in two forms.</p>
<p>One is the fixed ratio design (ray design) where the ratio of doses between two drugs is a constant. Another one is grid design which means all-possible combinations of drug doses are available.</p>
<p>Two papers have been published regarding to drug interaction index (IAI) by Lee et al, one in 2007 <a href="#lee2007interaction">Lee, J. J., Kong, M., Ayers, G. D., &amp; Lotan, R. (2007)</a> and one in 2009 <a href="#lee2009confidence">Lee, J. J., &amp; Kong, M. (2009)</a>. IAI=1 is the case for additive effect. IAI&gt;1 means antagonistic interaction while IAI&lt;1 means synergistic interaction. The Lee2007 paper described five methods to assess interaction: (1) Lowewe additivity model using interaction index (IAI) (2) Model of Greco et al 1990. This approach uses <span class="math">\(\alpha\)</span> as the metric and it can be related to IAI (3) Model of Machado and Robinson which uses a metric denoted as <span class="math">\(\eta\)</span> (4) Model of Plummer and Short which can also be linked to IAI through the parameter <span class="math">\(\beta_4\)</span> (5) Model of Carter et al that can be linked to IAI through the parameter <span class="math">\(\beta_{12}\)</span>. For more details of these models, please refer to <a href="#lee2007interaction">Lee, J. J., Kong, M., Ayers, G. D., &amp; Lotan, R. (2007)</a>.</p>
<p>The two papers by Lee et al discussed the fixed ratio design and the source code for doing this is incorporated into <strong>drexplorer2</strong>. To work on grid design, a fixed ratio from the data needs to be selected in order to apply their method. For example, the Lee2007 paper provided an example of grid design. A fixed ratio of 1 was specified in the paper. The specification of fixed ratio would affect the fitted median effect model (see definition in <a href="#lee2007interaction">Lee, J. J., Kong, M., Ayers, G. D., &amp; Lotan, R. (2007)</a>) for the drug mixture as well as estimation of IAI. As a result, IAI has a ratio dependent interpretation.</p>
<p>Below we load the UMSCC22B data from <a href="#lee2009confidence">Lee, J. J., &amp; Kong, M. (2009)</a>. This data has a fixed ratio design. The <code>fitIAI</code> function estimates IAI as well as its confidence interval after specifying dose1, dose2 and effect (between 0 and 1).</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">UMSCC22B</span>)

<span class="no">fit_fixedRay</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/fitIAI.html">fitIAI</a></span>(<span class="kw">d1</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>[, <span class="fl">1</span>], <span class="kw">d2</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>[, <span class="fl">2</span>], <span class="kw">e</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>[, <span class="fl">3</span>],
                       <span class="kw">name1</span> <span class="kw">=</span> <span class="st">'SCH66336'</span>, <span class="kw">name2</span> <span class="kw">=</span> <span class="st">'4HPR'</span>)</pre></body></html>
<p>The <code>plotIAI</code> function is then used to generate different plots including IAI versus response, IAI versus dose (predicted dose for the drug mixture, see equation (6) in <a href="#lee2007interaction">Lee, J. J., Kong, M., Ayers, G. D., &amp; Lotan, R. (2007)</a>), median effect plot and dose response curves. We can also plot IAI versus response as well as IAI versus dose in one figure by specifying mode=‘both’.</p>
<p>The median effect equation <a href="#chou1984quantitative">Chou, T. C., &amp; Talalay, P. (1984)</a> is as following: <span class="math">\[E=\frac{(d/D_{m})^m}{1+(d/D_{m})^m}\]</span></p>
<p>Sometimes replicated viability assays are performed. In such case, it is useful to examine if the experiments are reproducible.</p>
<p>A good metric is the <strong>Concordance Correlation Coefficient (CCC)</strong> that captures both the location shift as well as scale shift between the replicates. The <code>plotCCC</code> function can be used to compute CCC and visualize the replicated data.</p>
<p>where E is the induced effect of a drug with dose d whose median effective dose is <span class="math">\(D_{m}\)</span> and <span class="math">\(m\)</span> is a slope parameter.</p>
<p>This equation can be arranged as: <span class="math">\[logit(E)=m(log d - log D_{m})\]</span></p>
<p>The median effect plot shows logit(E) versus log10 dose; The dose response curve shows E versus dose. Below we plot IAI against response. The 95% confidence interval of IAI is shown in dashed line. It can be seen that there is significant synergistic interaction at small relative viability value (&lt;0.5). Although the IAI suggests antagonistic interaction at high viability values, the confidence band shows this is not statistically significant.</p>
<html><body><pre class="r"><span class="co">## IAI versus response</span>
<span class="fu"><a href="../reference/plotIAI.html">plotIAI</a></span>(<span class="no">fit_fixedRay</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">'IAI'</span>, <span class="kw">mode</span> <span class="kw">=</span> <span class="st">'response'</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-18-1.png" width="2400" style="display: block; margin: auto;"></p>
<p>Similarly, we can plot IAI against dose (the sum of dosages from two drugs). The following figure shows that there is significant synergism at high dosage.</p>
<html><body><pre class="r"><span class="co">## IAI versus dose</span>
<span class="fu"><a href="../reference/plotIAI.html">plotIAI</a></span>(<span class="no">fit_fixedRay</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">'IAI'</span>, <span class="kw">mode</span> <span class="kw">=</span> <span class="st">'dose'</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-19-1.png" width="2400" style="display: block; margin: auto;"></p>
<p>The median effect plot is shown below.</p>
<html><body><pre class="r"><span class="co">## median effect</span>
<span class="fu"><a href="../reference/plotIAI.html">plotIAI</a></span>(<span class="no">fit_fixedRay</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">'medianEffect'</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-20-1.png" width="4800" style="display: block; margin: auto;"></p>
<p>In <a href="#lee2007interaction">Lee, J. J., Kong, M., Ayers, G. D., &amp; Lotan, R. (2007)</a>, there is an example data (nl22B2) using grid design. Here we examine the estimate of IAI at different fixed ratios.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">nl22B2</span>)

<span class="no">fit_allPoss_1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/fitIAI.html">fitIAI</a></span>(<span class="kw">d1</span> <span class="kw">=</span> <span class="no">nl22B2</span>$<span class="no">schd</span>, <span class="kw">d2</span> <span class="kw">=</span> <span class="no">nl22B2</span>$<span class="no">hpr</span>, <span class="kw">e</span> <span class="kw">=</span> <span class="no">nl22B2</span>$<span class="no">y1</span>,
                        <span class="kw">name1</span> <span class="kw">=</span> <span class="st">'SCH66336'</span>, <span class="kw">name2</span> <span class="kw">=</span> <span class="st">'4HPR'</span>, <span class="kw">d2.d1.force</span> <span class="kw">=</span> <span class="fl">1</span>)
<span class="no">fit_allPoss_2</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/fitIAI.html">fitIAI</a></span>(<span class="kw">d1</span> <span class="kw">=</span> <span class="no">nl22B2</span>$<span class="no">schd</span>, <span class="kw">d2</span> <span class="kw">=</span> <span class="no">nl22B2</span>$<span class="no">hpr</span>, <span class="kw">e</span> <span class="kw">=</span> <span class="no">nl22B2</span>$<span class="no">y1</span>,
                        <span class="kw">name1</span> <span class="kw">=</span> <span class="st">'SCH66336'</span>, <span class="kw">name2</span> <span class="kw">=</span> <span class="st">'4HPR'</span>, <span class="kw">d2.d1.force</span> <span class="kw">=</span> <span class="fl">2</span>)</pre></body></html>
<p>From the median effect plot, we can find that there are 4 data points for drug mixtures at fixed ratio of 1 while only 2 data points are available at fixed ratio of 2.</p>
<html><body><pre class="r"><span class="fu"><a href="../reference/plotIAI.html">plotIAI</a></span>(<span class="no">fit_allPoss_1</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">'medianEffect'</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-22-1.png" width="2400" style="display: block; margin: auto;"></p>
<html><body><pre class="r"><span class="fu"><a href="../reference/plotIAI.html">plotIAI</a></span>(<span class="no">fit_allPoss_2</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">'medianEffect'</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-23-1.png" width="2400" style="display: block; margin: auto;"></p>
<p>Below we compare IAI estimated from the two scenarios.</p>
<html><body><pre class="r"><span class="fu"><a href="../reference/plotCCC.html">plotCCC</a></span>(<span class="no">fit_allPoss_1</span>$<span class="no">CI</span>$<span class="no">IAI</span>, <span class="no">fit_allPoss_2</span>$<span class="no">CI</span>$<span class="no">IAI</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-24-1.png" width="2400" style="display: block; margin: auto;"></p>
<pre><code>#&gt;     ccc s_shift l_shift  ccc_lo  ccc_hi      Cb    corr  mean_x  mean_y    sd_x 
#&gt;  0.9670  0.7872 -0.0996  0.9632  0.9704  0.9674  0.9996  2.0011  1.6774  3.6746 
#&gt;    sd_y 
#&gt;  2.8928</code></pre>
<div id="drug-interaction-index-with-model-selection" class="section level2">
<h2 class="hasAnchor">
<a href="#drug-interaction-index-with-model-selection" class="anchor"></a>- Drug Interaction Index With Model Selection</h2>
<p>The original Chou-Talalay interaction index approach uses median-effect equation to model drug combination data. This method assumes idealized log-linearity which usually does not hold on real data. Here built upon the drexplorer package which automatically selects the best model without constraining to log-linear model, we try to overcome this limitation by extending the interaction index approach to non-linear functions. Using the UMSCC22B data as an example below. We first fit the model and then plot the IAI estimates.</p>
<html><body><pre class="r"><span class="no">fitL_mod</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/fitIAI_mod.html">fitIAI_mod</a></span>(<span class="kw">d1</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>[, <span class="fl">1</span>], <span class="kw">d2</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>[, <span class="fl">2</span>], <span class="kw">e</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>[, <span class="fl">3</span>],
                       <span class="kw">name1</span> <span class="kw">=</span> <span class="st">'SCH66336'</span>, <span class="kw">name2</span> <span class="kw">=</span> <span class="st">'4HPR'</span>, <span class="kw">ratio</span> <span class="kw">=</span> <span class="fl">1</span>)

<span class="fu"><a href="../reference/plotIAI_mod.html">plotIAI_mod</a></span>(<span class="no">fitL_mod</span>, <span class="kw">mixtureDose</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'A+B'</span>))</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-25-1.png" width="4800" style="display: block; margin: auto;"></p>
<p>Compared to the original Chou-Talalay method, we now observed the dose-response curves fit better to the data and thus IAI estimates from this approach are more reliable. Since some response values are not achieved in the data, it is hard to extrapolate what dose would achieve those responses. This makes the estimation of IAI unavailable in some regions. Thus, this new approach is more conservative compared to the original Chou-Talalay method.</p>
</div>
</div>
<div id="drug-comb-fit-hsa-and-bliss-model" class="section level1">
<h1 class="hasAnchor">
<a href="#drug-comb-fit-hsa-and-bliss-model" class="anchor"></a>[Drug Comb] Fit HSA and Bliss Model</h1>
<p>Below we illustrate the application of HSA (Highest Single Agent) model and Bliss independence model. Both models first estimate the reference response of combination treatment (assumed to be theoretical additive effect) and then compare the observed response to the reference response for combination treatment. We compute the Area Under Curve (AUC) for the observed response and reference response and use their difference deltaAUC (AUC of observed response - AUC of reference response) to quantify the trend of synergism.</p>
<p>In terms of showing the curves of single and combination treatment, we use the projected dose which is <span class="math">\[d_{proj}=\sqrt{(d1^2 + d2^2)}\]</span></p>
<p>Based on the <span class="math">\(d_{proj}\)</span> dose of combination treatment, one can infer the corresponding dose of drug 1 (d1) and drug 2 (d2). That is, there is 1-to-1 correspondence among the 3 doses.</p>
<html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">drexplorer2</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">UMSCC22B</span>)

<span class="co">## fit HSA_Bliss model</span>
<span class="no">fit_hsa_bliss</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/fitHSA_ray.html">fitHSA_ray</a></span>(<span class="kw">d1</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>$<span class="no">dose1</span>, <span class="kw">d2</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>$<span class="no">dose2</span>, <span class="kw">e</span> <span class="kw">=</span> <span class="no">UMSCC22B</span>$<span class="no">e</span>,
                            <span class="kw">name1</span> <span class="kw">=</span> <span class="st">'SCH66336'</span>, <span class="kw">name2</span> <span class="kw">=</span> <span class="st">'4HPR'</span>, <span class="kw">islogd</span> <span class="kw">=</span> <span class="fl">FALSE</span>)

<span class="co">## plot deltaAUC_HSA</span>
<span class="fu"><a href="../reference/plotHSA_ray.html">plotHSA_ray</a></span>(<span class="no">fit_hsa_bliss</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'line'</span>, <span class="st">'HSA'</span>, <span class="st">'se'</span>),
            <span class="kw">main</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span>(<span class="st">'Delta AUC: HSA=%.2f'</span>, <span class="no">fit_hsa_bliss</span>$<span class="no">deltaAUC_HSA</span>),
            <span class="kw">legend</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">plotSetup</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-26-1.png" width="4680" style="display: block; margin: auto;"></p>
<p>The blue line in the above figure shows the estimates of additive effect from HSA model. Since the combination kills more than the additive effect, it suggests an trend towards synergy, quantified by delta AUC of -0.17, which is defined as the AUC of combination subtracted the AUC of additive effect.</p>
<html><body><pre class="r"><span class="co">## plot deltaAUC_Bliss</span>
<span class="fu"><a href="../reference/plotHSA_ray.html">plotHSA_ray</a></span>(<span class="no">fit_hsa_bliss</span>, <span class="kw">type</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'line'</span>, <span class="st">'Bliss'</span>, <span class="st">'se'</span>),
            <span class="kw">main</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span>(<span class="st">'Delta AUC: Bliss=%.2f'</span>, <span class="no">fit_hsa_bliss</span>$<span class="no">deltaAUC_Bliss</span>),
            <span class="kw">legend</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">plotSetup</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html>
<p><img src="ALL_files/figure-html/unnamed-chunk-27-1.png" width="4680" style="display: block; margin: auto;"></p>
<p>Similarly, the purple line in the above figure shows the estimates of additive effect from Bliss model. Since the combination kills less than the additive effect, it suggests an trend towards antagonistic effect, quantified by delta AUC of 0.06.</p>
<p>Notice that different definition of the baseline model for additive effect leads to different result for drug interactions. Usually, <strong>HSA model is a less stringent criteria compared to Bliss model</strong>.</p>
</div>
<div id="gui-usage" class="section level1">
<h1 class="hasAnchor">
<a href="#gui-usage" class="anchor"></a>[GUI Usage]</h1>
<p>GUI interface has been shipped with <strong>drexplorer2</strong> which is built upon the . After loading the <strong>drexplorer2</strong> package, typing</p>
<ul>
<li><strong><em>drexplorerGUI_1()</em></strong></li>
</ul>
<p>in the R console will bring out the GUI for fitting dose-response curves.</p>
<p>This GUI assumes input file in comma-separated format or tab-delimited format. The first column is assumed to be dose and the second column is assumed to be response. An optional header can be provided in the first row. Users can click the “Use example data” button for an example run using the <em>ryegrass</em> data. Result files will be saved in a folder called <strong>drexplorer_results</strong> at the working directory of R session including:</p>
<ul>
<li>DoseResponseCurve.pdf: the fitted dose response curve.</li>
<li>ICtable.csv: estimated IC (inhibitory concentration) values at different percentiles.</li>
<li>ICtable.csv: outlier status for each data point.</li>
</ul>
<p>Notice that example input file called <em>ryegrass.csv</em> will be dumped into the result folder if example data is used.</p>
<p>Similarly, typing</p>
<ul>
<li><strong><em>drexplorerGUI_2()</em></strong></li>
</ul>
<p>will bring out the GUI for drug-drug interaction analysis.</p>
<p>Users can run the UMSCC22B data set or the nl22B2 data set by clicking the “Use UMSCC22B data” or the “Use nl22B2 data” buttons. Example input files (UMSCC22B.csv and nl22B2.csv) will be dumped into the result folder <strong>drexplorer_results</strong> after the example run. Similar to the previous GUI, input file can be either a comma-separated file or tab-delimited file. Three columns are needed to run this GUI:</p>
<ul>
<li>The first column is assumed to be the dose of drug 1.</li>
<li>The second column is assumed to be the dose of drug 2.</li>
<li>The last column is assumed to be response under drug combinations.</li>
</ul>
<p>A multi-page pdf file will be generated to save various plots (e.g. IAIplot_for_nl22B2.pdf). A comma-separated file will be generated to save estimates of IAI as well as 95% confidence interval (e.g. IAI_CI_nl22B2.csv).</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Li Shen.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script><script>
  docsearch({
    
    
    apiKey: 'fbd8d79ed49f21fc9ca7b2cf601a3f5b',
    indexName: 'pkgdown',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
